#pragma once
//
// hf_fedvr.hpp
//
// Closed-shell Restricted Hartree-Fock (RHF) on a FEDVR basis, formulated in
// second quantization.
//
// In the DVR basis, the four-index electron-electron integral collapses to a
// two-index object  V_{pqrs} = δ_{pr} δ_{qs} V_{pq}  (see fedvr_basis.hpp).
// Substituting this into the standard closed-shell HF expressions yields
// remarkably compact formulas:
//
//   Density matrix (closed-shell):
//     P_{pq} = 2 Σ_{i ∈ occ} C_{pi} C_{qi}
//
//   Fock matrix (closed-shell, with Coulomb J and exchange K):
//     F_{pq} = h_{pq} + Σ_{rs} P_{rs} [ V_{pqrs} - (1/2) V_{prsq} ]
//            = h_{pq} + V_{pq} ( P_{pq} - (1/2) P_{qp} )
//   For real symmetric P this simplifies further to
//     F_{pq} = h_{pq} + (1/2) V_{pq} P_{pq}.
//
//   Total RHF energy:
//     E_RHF = (1/2) Σ_{pq} P_{pq} ( h_{pq} + F_{pq} )
//
// This header provides:
//   - rhf_density(C_occ)                      density matrix from occupied MO
//   - rhf_fock(h, V, P)                       Fock matrix from h, V_pq, P
//   - rhf_energy(h, V, C_occ)                 RHF total energy
//
//   Two solvers for the ground state (results should agree numerically):
//   1) rhf_imag_time(...)   imaginary-time RK4 + QR re-orthogonalization
//                           (matches the style of H_fedvr.hpp / He_fedvr.hpp)
//   2) rhf_scf(...)         Roothaan-Hall SCF: build F, diagonalize, take
//                           lowest N_occ eigenvectors as new C_occ
//
// In the closed-shell two-electron case (e.g. He) both methods reproduce the
// existing He_fedvr_GS.cpp result (-2.224120 Ha at L=20, n_e=10, n=8).
// For larger systems, the Hartree-only model in He_fedvr.hpp omits exchange,
// while the formulas here include it — but for two electrons in a single
// spatial orbital, exchange exactly cancels half of Coulomb, so the numbers
// coincide.  This is the formal extension toward Li, Be, ... and toward
// post-HF methods (MP2, CI, CCSD, VQE) which can directly reuse h, V_pq.
//

#include "fedvr_basis.hpp"

#include <Eigen/Dense>
#include <Eigen/Eigenvalues>
#include <Eigen/QR>
#include <Eigen/Sparse>
#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace fedvr
{

// ----------------------------------------------------------------------------
// Closed-shell density matrix:  P_{pq} = 2 Σ_{i ∈ occ} C_{pi} C_{qi}
// ----------------------------------------------------------------------------
inline Eigen::MatrixXd rhf_density(const Eigen::MatrixXd &C_occ)
{
    return 2.0 * (C_occ * C_occ.transpose());
}

// ----------------------------------------------------------------------------
// Closed-shell RHF Fock matrix in the FEDVR basis.
//
// Starting from the standard quantum-chemistry expression (physicist's
// notation for the two-electron integral):
//
//   F_{pq} = h_{pq} + Σ_{rs} P_{rs} [ (pr|qs) - (1/2) (pr|sq) ]
//
// In the DVR basis, the chemist's-notation integral collapses to
//   (pr|qs) = ∫∫ φ_p(x1) φ_r(x1) v(x1,x2) φ_q(x2) φ_s(x2) dx1 dx2
//          ≈ δ_{pr} δ_{qs} V_{pq}
// So:
//   Σ_{rs} P_{rs} (pr|qs) = Σ_{rs} P_{rs} δ_{pr} δ_{qs} V_{pq}
//                          = P_{pq} V_{pq} ?     -- only the (r=p, s=q) term
//                          NO: that yields δ_{pq} V_{pq} P_{pq} for diagonal F.
// Actually the trace contraction gives the *Coulomb* part as a diagonal
// operator with entries
//   J_p = Σ_q V_{pq} P_{qq},  i.e.  J = diag( V_pq · P_diag )
// (this is the Hartree potential at point p, generated by the diagonal of P).
// The exchange contribution is
//   Σ_{rs} P_{rs} (pr|sq) = Σ_{rs} P_{rs} δ_{ps} δ_{rq} V_{pr}
//                          = P_{qp} V_{pq}     (no sum)
// which, for real symmetric P, gives K_{pq} = V_{pq} P_{pq}.
//
// Therefore in the DVR basis:
//   F_{pq} = h_{pq} + δ_{pq} J_p - (1/2) V_{pq} P_{pq}
//   J_p    = Σ_q V_{pq} P_{qq}                (Hartree potential at site p)
//
// Sanity check (closed-shell two electrons, single spatial orbital ψ):
//   P_{pq} = 2 c_p c_q        (P_{qq} = 2 c_q^2)
//   J_p    = 2 Σ_q V_{pq} c_q^2          (matches He_fedvr.hpp::hartree_potential
//                                         times 2, which is correct for closed shell)
//   K-term: (1/2) V_{pq} P_{pq} = c_p c_q V_{pq}     (off-diagonal in general)
//   On the orbital ψ, F ψ = h ψ + (J - K/2) ψ, where for the one-orbital
//   closed-shell case K cancels exactly half of J:
//     2 J_p c_p - Σ_q V_{pq} c_q^2 c_p = (2-1) Σ_q V_{pq} c_q^2 c_p
//                                       = J_p c_p   (Hartree-only effective)
//   which is exactly what He_fedvr.hpp::apply_He_F implements for He.
// ----------------------------------------------------------------------------
inline Eigen::MatrixXd rhf_fock(const Eigen::SparseMatrix<double> &h,
                                const Eigen::MatrixXd &V_pq,
                                const Eigen::MatrixXd &P)
{
    const int N = static_cast<int>(P.rows());

    // Coulomb (diagonal): J_p = Σ_q V_{pq} P_{qq}
    Eigen::VectorXd P_diag = P.diagonal();
    Eigen::VectorXd J = V_pq * P_diag;

    // Exchange: K_{pq} = V_{pq} P_{pq}    (elementwise product)
    Eigen::MatrixXd K = V_pq.cwiseProduct(P);

    // F = h + diag(J) - (1/2) K
    Eigen::MatrixXd F = Eigen::MatrixXd(h);
    for (int p = 0; p < N; ++p)
        F(p, p) += J(p);
    F -= 0.5 * K;
    return F;
}

// ----------------------------------------------------------------------------
// Total RHF energy:  E = (1/2) Σ_{pq} P_{pq} ( h_{pq} + F_{pq} )
// (The standard "trace formula" works regardless of how F is constructed.)
// ----------------------------------------------------------------------------
inline double rhf_energy(const Eigen::SparseMatrix<double> &h,
                         const Eigen::MatrixXd &V_pq,
                         const Eigen::MatrixXd &C_occ)
{
    const Eigen::MatrixXd P = rhf_density(C_occ);
    const Eigen::MatrixXd F = rhf_fock(h, V_pq, P);
    const Eigen::MatrixXd hd = Eigen::MatrixXd(h);
    // 0.5 * Tr( P (h + F) )
    return 0.5 * (P.cwiseProduct(hd + F)).sum();
}

// ----------------------------------------------------------------------------
// QR-based orthonormalization of an N x N_occ matrix.
// In the DVR basis, the basis overlap S = I, so plain QR gives an
// orthonormal basis spanning the same subspace.
// ----------------------------------------------------------------------------
inline Eigen::MatrixXd qr_orthonormalize(const Eigen::MatrixXd &C)
{
    Eigen::HouseholderQR<Eigen::MatrixXd> qr(C);
    const int rows = static_cast<int>(C.rows());
    const int cols = static_cast<int>(C.cols());
    Eigen::MatrixXd Q = qr.householderQ() * Eigen::MatrixXd::Identity(rows, cols);
    return Q;
}

// ----------------------------------------------------------------------------
// Solver result types.
// ----------------------------------------------------------------------------
struct RHF_ImagTimeResult
{
    double E_RHF = 0.0;
    Eigen::MatrixXd C_occ;          // N x N_occ
    int iterations = 0;
    bool converged = false;
};

struct RHF_SCFResult
{
    double E_RHF = 0.0;
    Eigen::MatrixXd C_full;         // N x N (all MOs from final Fock)
    Eigen::MatrixXd C_occ;          // N x N_occ (lowest energy occupied MOs)
    Eigen::VectorXd orbital_energies; // size N (final Fock eigenvalues, ascending)
    int iterations = 0;
    bool converged = false;
};

// ----------------------------------------------------------------------------
// Solver 1: Imaginary-time RK4 propagation of occupied MOs.
//
//   ∂_τ C_occ = -F[C_occ] C_occ
//
// followed by QR re-orthonormalization each step (DVR overlap is I).
// Mirrors the style of H_fedvr.hpp / He_fedvr.hpp's RK4 routines.
// ----------------------------------------------------------------------------
inline RHF_ImagTimeResult rhf_imag_time(const Eigen::SparseMatrix<double> &h,
                                        const Eigen::MatrixXd &V_pq,
                                        int N_occ,
                                        const Eigen::MatrixXd &C_init,
                                        double dtau,
                                        int max_itr,
                                        double thresh)
{
    if (N_occ < 1)
        throw std::invalid_argument("rhf_imag_time: N_occ must be >= 1");
    if (C_init.cols() != N_occ)
        throw std::invalid_argument("rhf_imag_time: C_init.cols() must equal N_occ");

    const int N = static_cast<int>(h.rows());
    if (C_init.rows() != N)
        throw std::invalid_argument("rhf_imag_time: C_init.rows() must equal h.rows()");

    Eigen::MatrixXd C = qr_orthonormalize(C_init);

    auto apply_minus_F = [&](const Eigen::MatrixXd &C_in) -> Eigen::MatrixXd {
        // Build F using the *current* density (computed from C, not from C_in)
        // to keep the propagator linear in each RK4 substage. This is the
        // standard "frozen-Fock-during-substage" approach.
        // For consistency with He_fedvr.hpp::rk4_imag_step_He we instead rebuild
        // F from C_in itself (which makes the substages self-consistent).
        const Eigen::MatrixXd P_stage = rhf_density(C_in);
        const Eigen::MatrixXd F_stage = rhf_fock(h, V_pq, P_stage);
        return -(F_stage * C_in);
    };

    RHF_ImagTimeResult res;
    double prev_E = 1e30;

    for (int it = 0; it < max_itr; ++it)
    {
        const double E = rhf_energy(h, V_pq, C);
        const double diff = std::abs(E - prev_E);
        if (it > 0 && diff < thresh)
        {
            res.E_RHF = E;
            res.C_occ = C;
            res.iterations = it;
            res.converged = true;
            return res;
        }
        prev_E = E;

        // RK4 step
        const Eigen::MatrixXd k1 = apply_minus_F(C);
        const Eigen::MatrixXd k2 = apply_minus_F(C + 0.5 * dtau * k1);
        const Eigen::MatrixXd k3 = apply_minus_F(C + 0.5 * dtau * k2);
        const Eigen::MatrixXd k4 = apply_minus_F(C + dtau * k3);
        C += (dtau / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4);
        C = qr_orthonormalize(C);
    }

    res.E_RHF = rhf_energy(h, V_pq, C);
    res.C_occ = C;
    res.iterations = max_itr;
    res.converged = false;
    return res;
}

// ----------------------------------------------------------------------------
// Solver 2: Roothaan-Hall SCF (direct diagonalization of the Fock matrix).
//
//   F C = C ε    (DVR overlap S = I, so this is a plain symmetric eigenproblem)
//
// At each iteration: build P from current C_occ, build F, diagonalize F,
// take the lowest N_occ eigenvectors as the new C_occ.  Repeat until the
// total energy stops changing.
// ----------------------------------------------------------------------------
inline RHF_SCFResult rhf_scf(const Eigen::SparseMatrix<double> &h,
                             const Eigen::MatrixXd &V_pq,
                             int N_occ,
                             const Eigen::MatrixXd &C_init,
                             int max_itr,
                             double thresh)
{
    if (N_occ < 1)
        throw std::invalid_argument("rhf_scf: N_occ must be >= 1");
    if (C_init.cols() != N_occ)
        throw std::invalid_argument("rhf_scf: C_init.cols() must equal N_occ");

    const int N = static_cast<int>(h.rows());
    if (C_init.rows() != N)
        throw std::invalid_argument("rhf_scf: C_init.rows() must equal h.rows()");

    Eigen::MatrixXd C_occ = qr_orthonormalize(C_init);
    Eigen::MatrixXd C_full = Eigen::MatrixXd::Zero(N, N);
    Eigen::VectorXd eps = Eigen::VectorXd::Zero(N);

    RHF_SCFResult res;
    double prev_E = 1e30;

    for (int it = 0; it < max_itr; ++it)
    {
        const Eigen::MatrixXd P = rhf_density(C_occ);
        const Eigen::MatrixXd F = rhf_fock(h, V_pq, P);

        // Symmetrize for numerical safety (F should already be symmetric).
        const Eigen::MatrixXd F_sym = 0.5 * (F + F.transpose());

        Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> es(F_sym);
        if (es.info() != Eigen::Success)
            throw std::runtime_error("rhf_scf: Fock diagonalization failed");

        eps = es.eigenvalues();
        C_full = es.eigenvectors();
        // Lowest N_occ eigenvectors are the new occupied MOs.
        C_occ = C_full.leftCols(N_occ);

        // Energy at the *new* C_occ (use the freshly diagonalized orbitals)
        const double E = rhf_energy(h, V_pq, C_occ);
        const double diff = std::abs(E - prev_E);
        if (it > 0 && diff < thresh)
        {
            res.E_RHF = E;
            res.C_full = C_full;
            res.C_occ = C_occ;
            res.orbital_energies = eps;
            res.iterations = it + 1;
            res.converged = true;
            return res;
        }
        prev_E = E;
    }

    res.E_RHF = rhf_energy(h, V_pq, C_occ);
    res.C_full = C_full;
    res.C_occ = C_occ;
    res.orbital_energies = eps;
    res.iterations = max_itr;
    res.converged = false;
    return res;
}

} // namespace fedvr
