#pragma once
//
// hartree_fd.hpp
//
// First-quantization closed-shell Hartree+exchange mean-field machinery
// on the FD grid (multi-orbital generalization of the original He_GS.cpp).
//
// Mirrors FEDVR/He_fedvr.hpp in style and physics.  Uses the FD integral
// tensors from fd_basis.hpp.  Wavefunctions are kept real-valued
// (Eigen::VectorXd) since the GS Hamiltonian is real-symmetric and
// real eigenfunctions exist.
//
// Closed-shell single-orbital case (e.g. He, Z=2, N_e=2):
//   E[ψ] = 2 ⟨ψ|ĥ_Z|ψ⟩
//        + ∫∫ |ψ(x1)|^2 w(x1, x2) |ψ(x2)|^2 dx1 dx2
// Hartree-only effective Hamiltonian:
//   F[ψ] = T + diag(V_ne) + diag(W[|ψ|^2])
//   W_p = Σ_q V_pq |c_q|^2     (weights cancel in the DVR-like FD basis)
//
// Multi-orbital closed-shell case (e.g. Be, Z=4, N_occ=2):
//   The natural extension is the closed-shell RHF Fock operator
//     F_pq = h_pq + δ_pq Σ_q V_pq P_qq − (1/2) V_pq P_pq
//   where P_pq = 2 Σ_{i ∈ occ} C_pi C_qi.
//   For He (single orbital), the exchange term cancels half of Coulomb
//   and we recover the Hartree-only formula above.
//
// We provide *both* a Hartree-only single-orbital path (back-compat with
// the original He_GS.cpp result) and a general multi-orbital RHF path.
//

#include "fd_basis.hpp"

#include <Eigen/Dense>
#include <Eigen/QR>
#include <Eigen/Sparse>
#include <cmath>
#include <stdexcept>

namespace fd
{

// ----------------------------------------------------------------------------
// Hartree potential at every grid point, generated by a (single) orbital c.
//   W_p = Σ_q V_pq |c_q|^2
// In the DVR-like FD basis the equispaced weights cancel, leaving a clean
// matrix-vector product.  This matches FEDVR/He_fedvr.hpp::hartree_potential.
// ----------------------------------------------------------------------------
inline Eigen::VectorXd hartree_potential(const Eigen::MatrixXd &V_pq,
                                         const Eigen::VectorXd &c)
{
    return V_pq * c.array().square().matrix();
}

// ----------------------------------------------------------------------------
// Single-orbital Hartree-only effective Hamiltonian × vector.
//   (T + V_ne + diag(W)) v
// ----------------------------------------------------------------------------
inline Eigen::VectorXd apply_F_hartree(const Eigen::SparseMatrix<double> &T,
                                       const Eigen::VectorXd &V_ne,
                                       const Eigen::VectorXd &W,
                                       const Eigen::VectorXd &v)
{
    Eigen::VectorXd out = (T * v).eval();
    out.array() += (V_ne.array() + W.array()) * v.array();
    return out;
}

// One imaginary-time RK4 step for the closed-shell single-orbital
// Hartree-only mean-field equation:
//   ∂_τ c = -(T + V_ne + W[|c|^2]) c
// followed by L2 normalization.
inline void rk4_imag_step_hartree(const Eigen::SparseMatrix<double> &T,
                                  const Eigen::VectorXd &V_ne,
                                  const Eigen::MatrixXd &V_pq,
                                  Eigen::VectorXd &c,
                                  double dtau)
{
    auto F_minus = [&](const Eigen::VectorXd &v) -> Eigen::VectorXd {
        const Eigen::VectorXd W = hartree_potential(V_pq, v);
        return -apply_F_hartree(T, V_ne, W, v);
    };

    const Eigen::VectorXd k1 = F_minus(c);
    const Eigen::VectorXd k2 = F_minus(c + 0.5 * dtau * k1);
    const Eigen::VectorXd k3 = F_minus(c + 0.5 * dtau * k2);
    const Eigen::VectorXd k4 = F_minus(c + dtau * k3);
    c += (dtau / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4);
    c /= c.norm();
}

// ----------------------------------------------------------------------------
// Energies for the closed-shell *single-orbital* Hartree-only model.
//   E1 = 2 ⟨c|ĥ_Z|c⟩
//   E2 = ⟨ρ|V_pq|ρ⟩ where ρ_p = |c_p|^2
//   E_tot = E1 + E2
// (For He this reproduces the original FD/legacy/He_GS.cpp output.)
// ----------------------------------------------------------------------------
struct HartreeEnergies
{
    double E1 = 0.0;
    double E2 = 0.0;
    double Etot = 0.0;
};

inline HartreeEnergies compute_energies_hartree(const Eigen::SparseMatrix<double> &T,
                                                const Eigen::VectorXd &V_ne,
                                                const Eigen::MatrixXd &V_pq,
                                                const Eigen::VectorXd &c)
{
    Eigen::VectorXd Hc = (T * c).eval();
    Hc.array() += V_ne.array() * c.array();
    const double e1_per_electron = c.dot(Hc);

    const Eigen::VectorXd c2 = c.array().square();
    const double e2 = c2.dot(V_pq * c2);

    HartreeEnergies res;
    res.E1 = 2.0 * e1_per_electron;
    res.E2 = e2;
    res.Etot = res.E1 + res.E2;
    return res;
}

// ----------------------------------------------------------------------------
// Multi-orbital closed-shell RHF in the *first-quantization style*:
// the same RK4 integrator advances an N×N_occ matrix of orbital coefficients
// under the closed-shell Fock operator
//   F_pq = h_pq + δ_pq J_p − (1/2) V_pq P_pq
//   P_pq = 2 Σ_i C_pi C_qi
//   J_p  = Σ_q V_pq P_qq
// (numerically identical to FEDVR/hf_fedvr.hpp's RHF, just on the FD grid).
//
// Provided here for symmetry with the single-orbital Hartree-only routines.
// For Be we also have FD/Be_fd_HF.cpp (second-quantization style) which
// reuses FEDVR/hf_fedvr.hpp directly.
// ----------------------------------------------------------------------------
inline Eigen::MatrixXd qr_orthonormalize(const Eigen::MatrixXd &C)
{
    Eigen::HouseholderQR<Eigen::MatrixXd> qr(C);
    const int rows = static_cast<int>(C.rows());
    const int cols = static_cast<int>(C.cols());
    Eigen::MatrixXd Q = qr.householderQ() * Eigen::MatrixXd::Identity(rows, cols);
    return Q;
}

// Closed-shell density: P_{pq} = 2 Σ_{i ∈ occ} C_{pi} C_{qi}
inline Eigen::MatrixXd rhf_density(const Eigen::MatrixXd &C_occ)
{
    return 2.0 * (C_occ * C_occ.transpose());
}

// Closed-shell RHF Fock matrix in the (DVR-like) FD basis:
//   F_pq = h_pq + δ_pq J_p − (1/2) V_pq P_pq
inline Eigen::MatrixXd rhf_fock(const Eigen::SparseMatrix<double> &h,
                                const Eigen::MatrixXd &V_pq,
                                const Eigen::MatrixXd &P)
{
    const int N = static_cast<int>(P.rows());
    const Eigen::VectorXd P_diag = P.diagonal();
    const Eigen::VectorXd J = V_pq * P_diag;
    const Eigen::MatrixXd K = V_pq.cwiseProduct(P);
    Eigen::MatrixXd F = Eigen::MatrixXd(h);
    for (int p = 0; p < N; ++p)
        F(p, p) += J(p);
    F -= 0.5 * K;
    return F;
}

inline double rhf_energy(const Eigen::SparseMatrix<double> &h,
                         const Eigen::MatrixXd &V_pq,
                         const Eigen::MatrixXd &C_occ)
{
    const Eigen::MatrixXd P = rhf_density(C_occ);
    const Eigen::MatrixXd F = rhf_fock(h, V_pq, P);
    const Eigen::MatrixXd hd = Eigen::MatrixXd(h);
    return 0.5 * (P.cwiseProduct(hd + F)).sum();
}

// First-quantization-style RK4 step for the multi-orbital RHF:
//   ∂_τ C_occ = -F[C_occ] C_occ
// followed by QR re-orthonormalization (DVR overlap is I).
inline void rk4_imag_step_rhf(const Eigen::SparseMatrix<double> &h,
                              const Eigen::MatrixXd &V_pq,
                              Eigen::MatrixXd &C_occ,
                              double dtau)
{
    auto apply_minus_F = [&](const Eigen::MatrixXd &C_in) -> Eigen::MatrixXd {
        const Eigen::MatrixXd P_stage = rhf_density(C_in);
        const Eigen::MatrixXd F_stage = rhf_fock(h, V_pq, P_stage);
        return -(F_stage * C_in);
    };

    const Eigen::MatrixXd k1 = apply_minus_F(C_occ);
    const Eigen::MatrixXd k2 = apply_minus_F(C_occ + 0.5 * dtau * k1);
    const Eigen::MatrixXd k3 = apply_minus_F(C_occ + 0.5 * dtau * k2);
    const Eigen::MatrixXd k4 = apply_minus_F(C_occ + dtau * k3);
    C_occ += (dtau / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4);
    C_occ = qr_orthonormalize(C_occ);
}

} // namespace fd
